routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| 
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Home
Route::get('/', ['as' => 'main', 'uses' => 'MainController@index']);

//buscar por tipo do imóvel
Route::get('/imoveis/tipo/{id}', ['as' => 'buscarPorTipo', 'uses' => 'ImovelController@imoveisPorTipo']);

//buscar por finalidade
Route::get('/imoveis/finalidade/{id}', ['as' => 'buscarPorFinalidade', 'uses' => 'ImovelController@imoveisPorFinalidade']);

//buscar um imóvel específico
Route::get('/imovel/{id}', ['as' => 'buscarImovel', 'uses' => 'ImovelController@show']);

Route::get('/servicos', function() {
    return view('servicos');
});

Route::get('/servico/{id}', ['as' => 'buscarServico', 'uses' => 'ServicoController@show']);
Route::get('/simulacao/{id}', ['as' => 'buscarSimulacao', 'uses' => 'SimulacaoController@show']);
Route::get('/depoimentos', ['as' => 'depoimentos', 'uses' => 'MainController@depoimentos']);
Route::get('/contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::get('/onde-estamos', ['as' => 'onde-estamos', 'uses' => 'MainController@localizacoes']);
Route::get('/empresa', ['as' => 'empresa', 'uses' => 'InstitucionalController@sobreNos']);

//realiza a busca (formulário de busca de imóveis)
Route::post('realizar-busca', ['as' => 'realizar-busca', 'uses' => 'MainController@realizarBusca']);

//Envia um e-mail (aba contato) 
Route::post('/sendContato', ['as' => 'sendContato', 'uses' => 'SendController@send']);

//Envia um e-mail de dúvida para o corretor do imóvel
Route::post('/sendEmailCorretor', ['as' => 'sendEmailCorretor', 'uses' => 'SendController@sendEmailCorretor']);

Route::post('/enviarSolicitacao', ['as' => 'enviarSolicitacao', 'uses' => 'SendController@enviarSolicitacao']);

/* Painel Administrador */
Route::group(['prefix' => 'administrador', 'middleware' => 'auth'], function() {

    Route::get('/', ['as' => 'administrador', 'uses' => function() {
        return view('painel.comum');
    }]);

    //Tipos
    Route::resource('tipos', 'TipoController');
    Route::post('alterarTipo', ['as' => 'alterarTipo', 'uses' => 'TipoController@update']);
    
    //Configurações
    Route::resource('configuracoes', 'ConfiguracaoController');
    
    //Atributos
    Route::resource('atributos', 'AtributoController');
    Route::post('alterarAtributo', ['as' => 'alterarAtributo', 'uses' => 'AtributoController@update']);

    //ver imóveis
    Route::resource('ver-imoveis', 'ImovelController');
    Route::put('alterarPosicaoDestaque', ['as' => 'alterarPosicaoDestaque', 'uses' => 'ImovelController@alterarPosicaoDestaque']);

    //rota que altera a imagem de capa de um imóvel
    Route::post('ver-imoveis/alterarCapa/', ['as' => 'alterar-capa', 'uses' => 'ImovelController@alterarCapa']);

    Route::get('ver-imoveis/buscarCapa/{id}', ['as' => 'buscar-capa', 'uses' => 'ImovelController@buscarCapa']);

    //rota que irá excluir uma imagem
    Route::post('ver-imoveis/excluirImagem', ['as' => 'excluir-imagem', 'uses' => 'ImovelController@excluirImagem']);

    Route::get('ordenarDestaques', ['as' => 'ordenarDestaques', 'uses' => 'ImovelController@ordenarDestaques']);

    //rota que irá alterar o status de um imóvel
    Route::get('alterar-status/{id}', ['as' => 'alterar-status', 'uses' => 'ImovelController@alterarStatus']);
    //rota que irá definir o destaque
    Route::get('alterar-destaque/{id}', ['as' => 'alterar-destaque', 'uses' => 'ImovelController@alterarDestaque']);
    //rota que irá alterar se o imóvel está vendido ou não
    Route::get('alterar-vendido/{id}', ['as' => 'alterar-vendido', 'uses' => 'ImovelController@alterarVendido']);

    //Onde estamos
    Route::resource('onde-estamos', 'LocalizacaoController');
    Route::post('alterarLocalizacao', ['as' => 'alterarLocalizacao', 'uses' => 'LocalizacaoController@update']);

    //Depoimentos
    Route::resource('depoimentos', 'DepoimentoController');
    Route::post('alterarDepoimento', ['as' => 'alterarDepoimento', 'uses' => 'DepoimentoController@update']);

    //Serviços
    Route::resource('/servicos', 'ServicoController');
    Route::post('alterarServico', ['as' => 'alterarServico', 'uses' => 'ServicoController@update']);

    //Slides
    Route::resource('/slides', 'SlideController');
    Route::post('alterarSlide', ['as' => 'alterarSlide', 'uses' => 'SlideController@update']);

    //Institucional
    Route::resource('institucional', 'InstitucionalController');

    Route::get('/adicionar-imovel', function() {
        return view('painel.adicionar-imovel.adicionar-imovel');
    });

    Route::resource('/simulacoes', 'SimulacaoController');
    Route::post('alterarSimulacao', ['as' => 'alterarSimulacao', 'uses' => 'SimulacaoController@update']);
    Route::get('/buscar-cidades/{id}', ['as' => 'buscar-cidades', 'uses' => 'CidadeController@buscarCidades']);
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/painel/comum.blade.php
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Painel de controle</title>

	<link rel="stylesheet" href="{{ asset('/painel/assets/plugins/morris/morris.css') }}">
	<link rel="shortcut icon" type="image/png" href="{{ asset('/painel/img/favicon.png') }}">
	<link href="{{ asset('/painel/assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset('/painel/assets/css/alt.css') }}" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
	<link href="{{ asset('/painel/assets/css/core.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset('/painel/assets/css/components.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset('/painel/assets/css/icons.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset('/painel/assets/css/pages.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset('/painel/assets/css/menu.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset('/painel/assets/css/responsive.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset('/painel/assets/plugins/switchery/css/switchery.min.css') }}" rel="stylesheet" />
	<link href="{{ asset('/painel/assets/plugins/summernote/summernote.css') }}" rel="stylesheet" />
	<link href="{{ asset('/painel/assets/plugins/select2/css/select2.min.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset('/painel/assets/plugins/dropzone/dropzone.css') }}" rel="stylesheet" type="text/css" />

	<script src="{{ asset('/painel/assets/js/modernizr.min.js') }}"></script>

</head>

<body>

	<!-- Navigation Bar-->
	<header id="topnav">
		<div class="topbar-main">
			<div class="container">
				<div class="logo bot10">
					<a href="./">
						<img src="{{ asset('/painel/img/logo.png') }}" class="img-responsive hidden-xs" alt="">
					</a>
					<a href="./">
						<img src="{{ asset('/painel/img/logoMobile.png') }}" class="img-responsive visible-xs logoMobile" alt="">
					</a>
				</div>

				<div class="menu-extras">
					<ul class="nav navbar-nav navbar-right pull-right">
						<li class="dropdown navbar-c-items">
							<div class="btn-group" style="margin-top: 15px;">
								<button type="button" class="btn btn-laranja dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="false">
									<i class="fa fa-user"></i>
									<span class="hidden-xs">Olá {{ $user->email }}</span>
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu" role="menu">
									<li>
										{!! Form::open(array('route' => 'logout', 'method' => 'POST'), ['class' => 'fa fa-angle-right text-custom m-r-10']) !!} {!!
										csrf_field() !!}
										<input type="submit" value="Sair"> {!! Form::close() !!}
									</li>
								</ul>
							</div>
						</li>
					</ul>
					<div class="menu-item">
						<!-- Mobile menu toggle-->
						<a class="navbar-toggle">
							<div class="lines">
								<span></span>
								<span></span>
								<span></span>
							</div>
						</a>
						<!-- End mobile menu toggle-->
					</div>
				</div>

			</div>
		</div>

		<div class="navbar-custom">
			<div class="container">
				<div id="navigation">
					<!-- Navigation Menu-->
					<ul class="navigation-menu">

						<li>
							<a href="{{ route('main') }}">
								<i class="fa fa-home"></i>Início
							</a>
						</li>

						<li>
							<a href="{{ route('institucional.index') }}">
								<i class="fa fa-building"></i> Institucional</a>
						</li>

						<li>
							<a href="{{ route('simulacoes.index') }}">
								<i class="fa fa-calculator"></i> Simulações </a>
						</li>

						<li>
							<a href="{{ route('slides.index') }}">
								<i class="fa fa-image"></i> Slides</a>
						</li>

						<li class="has-submenu">
							<a href="{{ route('ver-imoveis.index') }}">
								<i class="fa fa-home"></i>Imóveis</a>
							<ul class="submenu">
								<li>
									<a href="{{ route('ver-imoveis.index') }}">Ver imóveis</a>
								</li>

								<li>
									<a href="{{ route('tipos.index') }}">Tipos</a>
								</li>

								<li>
									<a href="{{ route('atributos.index') }}">Atributos</a>
								</li>
							</ul>
						</li>

						<li>
							<a href="{{ route('servicos.index') }}">
								<i class="fa fa-wrench" aria-hidden="true"></i>Serviços</a>
						</li>

						<li>
							<a href="{{ route('depoimentos.index') }}">
								<i class="fa fa-comments" aria-hidden="true"></i>Depoimentos</a>
						</li>

						<li>
							<a href="{{ route('onde-estamos.index') }}">
								<i class="fa fa-map-marker" aria-hidden="true"></i>Onde Estamos</a>
						</li>

						<li>
							<a href="{{ route('configuracoes.index') }}">
								<i class="fa fa-cogs"></i>Configurações</a>
						</li>
						
					</ul>
				</div>
			</div>
		</div>
	</header>

	@include('painel.inc.modal.usuarios.alterar-senha')

	<!-- Aqui vem o conteúdo -->

	@yield('corpo')

	<script src="{{ asset('/painel/assets/js/jquery.min.js') }}"></script>
	<script src="{{ asset('/painel/assets/js/bootstrap.min.js') }}"></script>
	<script src="{{ asset('/painel/assets/js/detect.js') }}"></script>
	<script src="{{ asset('/painel/assets/js/fastclick.js') }}"></script>
	<script src="{{ asset('/painel/assets/js/jquery.slimscroll.js') }}"></script>
	<script src="{{ asset('/painel/assets/js/jquery.blockUI.js') }}"></script>
	<script src="{{ asset('/painel/assets/js/waves.js') }}"></script>
	<script src="{{ asset('/painel/assets/js/wow.min.js') }}"></script>
	<script src="{{ asset('/painel/assets/js/jquery.nicescroll.js') }}"></script>
	<script src="{{ asset('/painel/assets/js/jquery.scrollTo.min.js') }}"></script>
	<script src="{{ asset('/painel/assets/plugins/dropzone/dropzone.js') }}"></script>
	<script src="{{ asset('/js/jquery.mask.js') }}" type="text/javascript"></script>

	<!--Summernote js-->
	<script src="{{ asset('/painel/assets/plugins/summernote/summernote.js') }}"></script>

	<!-- scripts das views -->
	@yield('scripts')

	<!-- App core js -->
	<script src="{{ asset('/painel/assets/js/jquery.core.js') }}"></script>
	<script src="{{ asset('/painel/assets/js/jquery.app.js') }}"></script>

	<script>
		jQuery(document).ready(function(){

                $('.summernote').summernote({
                    height: 250,                 // set editor height
                    minHeight: null,             // set minimum height of editor
                    maxHeight: null,             // set maximum height of editor
                    focus: false,               // set focus to editable area after initializing summernote
                    toolbar: [
                        // [groupName, [list of button]]
                        ['style', ['bold', 'italic', 'underline', 'clear']],
                        ['font', ['strikethrough', 'superscript', 'subscript']],
                        ['fontsize', ['fontsize']],
                        ['color', ['color']],
                        ['para', ['ul', 'ol', 'paragraph']],
                        ['height', ['height']]
                      ]
                });

                $('.inline-editor').summernote({
                    airMode: true
                });

                $('.money').mask('000.000.000.000.000,00', {reverse: true});

            });
	</script>

</body>

</html>

resources/views/painel/index.blade.php
<?php $menu = "inicio"; ?>

@extends('comum')
<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="portlet">
                    <div class="portlet-heading bg-inverse">
                        <h3 class="portlet-title">
                            <i class="fa fa-home"></i> Início
                        </h3>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card-box">
                  
                </div>
            </div>
        </div>

resources/views/painel/modeloPainel.blade.php
@extends('painel.comum')

@section('corpo')

    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet">
                        <div class="portlet-heading bg-inverse">
                            <h3 class="portlet-title">
                                @yield('titulo')
                            </h3>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>

            @if(Session::has('success'))
                <div class="alert alert-info">
                    {{ Session::get('success') }}
                </div>
            @endif

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row">
                <div class="col-md-12">
                    <div class="card-box">
                        <div class="table-wrapper">
                            <div class="btn-toolbar bot20">
                                <a href="" data-toggle="modal" data-target="#adicionar" type="button" class="btn btn-laranja">Adicionar</a>
                            </div>

                            <div class="table-responsive">
                                @yield('tabela')
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection